### ISSUE TITLE
Not working with the newest full Raspbian image

### ISSUE THREAD

**Issue by ToMe25** [jdonald/raspbian-multiarch#2]
I have recently tried to use this on a fresh copy of the official Raspbian image with the 64 bit kernel enabled(just an added arm_64bit=1 to the /boot/config.txt), but it didn't really work.

First it made some errors due to changed version numbers,
than it had problems because it wasn't changing all the needed version numbers in the mesa libs and a missing dependency.

However i was able to fix all that(i can make a PR with the changes i did if you want), after that it said it misses `libllvm7:arm64` and `libstdc++6:arm64`, as i had problems earlier with adding them to the script i installed them and all their dependencies manually just for a test run and would have tried to integrate them into the script later.

Than i restarted the script and it first created all the stealthrpi packages as it for some reason thinks there is one too much stealthrpi file, but as it came to the point where it last time missed some dependencies this time it printed 
```
dpkg: error processing archive /tmp/apt-dpkg-install-PjtObd/44-libgl1-mesa-dri_18.3.6-2_arm64.deb (--unpack):
 trying to overwrite shared '/usr/share/drirc.d/00-mesa-defaults.conf', which is different from other instances of package libgl1-mesa-dri:arm64
```
and than crashed with the message
```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-PjtObd/44-libgl1-mesa-dri_18.3.6-2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
and i am currently unable to fix that.

This is the almost full log of the second run: [szZSQsN2](https://pastebin.com/szZSQsN2), its not a full log because the console didn't save the start as it was too much text, before this the only things happening were downloading the stealthrpi packets and a list of the stealthrpi packages.

**Comment by ToMe25** [comment]
@jdonald any news about this?

**Comment by jdonald** [comment]
Odd that I don’t get notifications about new issues until you @ me! I need to check the GitHub email settings on all of my repos.

Please make that PR with your changes and I’ll work on top of it to get this working with the latest image.

**Comment by ToMe25** [comment]
Seems to be fixed thanks :)
Having it install Firefox was nice tho.

**Comment by jdonald** [comment]
Yeah you can see how I used a patch to make `00-mesa-defaults.conf` from Mesa 19.2 match the one from Mesa 18.3, but at the end I overwrite the file with an even newer config file from the mesa-v3_19.3 tarball.

Back when I examined this for Buster in July I ran into a major problem with libasound2 because Debian/Raspbian did something really bad with libopusfile in a single conflicting location for both armhf and aarch64. Without resolving that I couldn't install 64-bit libsdl2-mixer-2.0-0 and therefore no 64-bit Doom. I hoped the Debian team might fix it, but until then I basically gave up on supporting anything graphical. I thought I had already commented out Doom, Firefox, and Minetest, but apparently not so I did that yesterday.

The fact that you got so far on the GL part made it seem possible, so I got things to the point of running glxgears. Note though I had to cheat at the end and unpack a custom tarball because Debian Buster uses too old a version of Mesa to support accelerated graphics on the Pi 4.

The libopusfile thing isn't insurmountable, but considering we'd have to patch at least one Debian package (so far we've only hacked Raspbian packages), for me it sounded too messy to be worthwhile.

The Firefox arm64 demo made sense when this was originally built for Stretch because 32-bit Firefox (and Firefox ESR) was broken on Debian/Raspbian for more than a year. With Buster this is no longer the case because they fixed the 32-bit build. To install the latest major version of Firefox (not Firefox ESR) on Buster, see these instructions: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=248269&p=1516981#p1516981

64-bit Firefox on Raspbian can be used for experimentation but it isn't good for everyday use. As an artifact of the regrettable hardware design and OpenSSL's AES implementation, https browsing on any Pi board is significantly slower than 32-bit. Same goes for Chromium.

**Comment by ToMe25** [comment]
I first tried to just install the default firefox 32bit package,
but that wanted to remove like half the 64bit packages,
then i tried adding the mozilla repo like this script earlier did and then just installing firefox 64 bit,
but it just didn't knew a package named "firefox:arm64",
so i ended up installing firefox esr 64 bit and it just works currently,
i can't realy say anyting about its performance, compared to the 32 bit one as i don't have that,
but it seems better than the 32 bit chromium.

Thanks again for your help most stuff seems to work now :)

**Comment by jdonald** [comment]
This project is expected to continue to break periodically, and may have already with the latest or upcoming Mesa upgrade supporting OpenGL ES 3.1.

Yesterday I came across a thread on the forums: [
experimental support for multiarch with Raspbian and Debian arm64](https://www.raspberrypi.org/forums/viewtopic.php?t=254027)
That was back in October and seems to be supported by a couple Raspberry Pi staff members. Wondering how well it works so far?

jdonald/raspbian-multiarch was always meant to be a proof-of-concept, hoping one day to be unneeded when the Pi Foundation properly supports multiarch with upstream packages.

**Comment by ToMe25** [comment]
Thanks for sending that link, i didn't know that something like this is worked on, even tho i searched the forum for some time.
